-- AlterEnum
ALTER TYPE "TournamentStatus" ADD VALUE 'REGISTRATION_OPEN';
ALTER TYPE "TournamentStatus" ADD VALUE 'REGISTRATION_CLOSED';
ALTER TYPE "TournamentStatus" ADD VALUE 'IN_PROGRESS';
ALTER TYPE "TournamentStatus" ADD VALUE 'COMPLETED';
